spring:

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  mvc:
    throw-exception-if-no-handler-found: true

  jackson:
    default-property-inclusion: non_null
    serialization.write-dates-as-timestamps: false

server:
  context-path: /app
  port: 8081

security:
  basic:
    enabled: false

logging:
  level:
    root: info
    com.company.app: debug

flyway:
  enabled: false

levelog:
  kafka:
    enabled: true


spring.boot.admin:
  url: http://mng:8080/mng/
  client.health-url: http://app:8080/app/mng/health/
  client.management-url: http://app:8080/app/mng/
  client.service-url: http://app:8080/app/

management:
  context-path: /mng
  security.enabled: false